license="MIT"
modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Harleyoc1/DynamicTreesVampirism/issues"

[[mods]]
modId="dtvampirism"
version="${file.jarVersion}"
displayName="Dynamic Trees for Vampirism"
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/Vampirism.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-vampirism"
logoFile="dtv-icon.png"
credits="Groupix05"
authors="Harley O'Connor"
description='''
Adds Dynamic Trees compatibility to Vampirism and Werewolves.
'''

[[dependencies.dtvampirism]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtvampirism]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtvampirism]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.3.6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtvampirism]]
    modId="vampirism"
    mandatory=true
    versionRange="[1.10.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtvampirism]]
    modId="werewolves"
    mandatory=false
    versionRange="[2.0.0.0,)"
    ordering="AFTER"
    side="BOTH"
