license="MIT"
modLoader="javafml"
loaderVersion="[43,46)"
issueTrackerURL="https://github.com/Harleyoc1/DynamicTreesVampirism/issues"

[[mods]]
modId="dtvampirism"
version="${file.jarVersion}"
displayName="Dynamic Trees for Vampirism"
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/Vampirism.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-vampirism"
logoFile="dtv-icon.png"
credits=""
authors="Harley O'Connor"
description='''
Adds Dynamic Trees compatibility to Vampirism.
'''

[[dependencies.dtvampirism]]
    modId="forge"
    mandatory=true
    versionRange="[43,46)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtvampirism]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtvampirism]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.1.0-BETA1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtvampirism]]
    modId="vampirism"
    mandatory=true
    versionRange="[1.9.4,)"
    ordering="AFTER"
    side="BOTH"