license="MIT"
modLoader="javafml"
loaderVersion="[36,37)"
issueTrackerURL="https://github.com/Harleyoc1/DynamicTreesVampirism/issues"

[[mods]]
modId="dtvampirism"
version="${file.jarVersion}"
displayName="Dynamic Trees for Vampirism"
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/Vampirism.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-vampirism"
logoFile="dtv-icon.png"
credits=""
authors="Harley O'Connor"
description='''
Adds Dynamic Trees compatibility to Vampirism.
'''

[[dependencies.dtvampirism]]
    modId="forge"
    mandatory=true
    versionRange="[36,37)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtvampirism]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtvampirism]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.10.0-Beta34,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtvampirism]]
    modId="vampirism"
    mandatory=true
    versionRange="[1.7.10,)"
    ordering="AFTER"
    side="BOTH"